# configs/rules/base_rules.yaml
# version: "1.0"

basic_table:
#规则值,用于自定义匹配规则
    pattern:
    #用于匹配相关的节点
        type : "node"
        level: "current"
        #匹配的节点层级
        class_name: "table"
        #匹配的类名
    conditions:
    #匹配上的节点继续时所需要满足的条件,对于两个同级的列表项，默认作为or条件使用，只要有一个条件满足就代表该条件校验通过，权重值会直接取所有被满足的条件的最大值
        - And :
            - condition_true:
                weight : 2
            - parent_class:
                # 匹配父类是否为某一个特定的类
                class_name : "Expression"
                weight : 7
            - or:
                - condition_true:
                    weight: 2
                - sub_class:
                    - class_name: "Update"
                    - weight: 8


    actions:
    #满足条件时执行如下动作
        - add_node:
            #add_node将该节点添加至图之中
        - property_values:
            #获取@property_value的属性
            - db: schema
              #方法名：属性和备注(该名称作为节点的key存储)
            - catalog: catalog
            - alias: table_alias
            - name : table_name


basic_select:
    pattern:
        type: "node"
        level: "current"
        class_name: "select"
    conditions:
        - condition_true:
            weight: 3
    actions:
        - scopes: select
          # scopes的create只能限定在如下的节点之内 select,delete,update,merge
        - add_node:
        - set_stage : select



basic_from:
    pattern:
        type: "node"
        level: "current"
        class_name: "from"
    conditions:
        - condition_true:
            weight: 2
    actions:
        - add_node:
        - set_stage : from

basic_where:
    pattern:
        type: "node"
        level: "current"
        class_name: "where"
    conditions:
        - condition_true:
            weight: 2
    actions:
        - add_node:
        - set_stage : where

basic_join:
    pattern:
        type: "node"
        level: "current"
        class_name: "join"
    conditions:
        - condition_true:
            weight: 2
    actions:
        - add_node:
        - set_stage : joins
        - args_values:
              #按照直接获取当前节点的表达式参数值
              - side:
                #side参数表示两张表join方式
                    node_key: join_side
                    # 参数值在存储时所用的键值
                    keep_missing : True
                    # value不存在时是否依旧记录该键值对
                    default_value: inner
                    # value不存在时使用的默认值




basic_column:
    pattern:
        type: "node"
        level: "current"
        class_name: "column"
    conditions:
        - condition_true:
            weight: 3
    actions:
        - add_node:
        - property_values:
              #获取@property_value的属性
              - db: schema
                  #方法名：属性和备注
              - catalog: catalog
              - alias: table_alias
              - name: table_name

basic_alias:
    pattern:
        type: "node"
        level: "current"
        class_name: "alias"
    conditions:
        - condition_true:
            weight: 2
    actions:
        - add_node:
        - property_values:
              #获取@property_value的属性
              - output_name: output_name

basic_with:
    pattern:
        type: "node"
        level: "current"
        class_name: "alias"
    conditions:
        - condition_true:
            weight: 2
    actions:
        - add_node:
        - set_stage: with
        - property_values:
              #获取@property_value的属性
              - recursive: recursive_flag
                #recursive用来标志改语句是否是递归的
        - args_values:
              #按照直接获取当前节点的表达式参数值
            - search:
              #search参数用来标记cte是一个标量cte
                  node_key: search_flag
                  # 参数值在存储时所用的键值
                  keep_missing: True
                  # value不存在时是否依旧记录该键值对
